# Generated by Django 4.2.5 on 2023-09-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_remove_customer_first_name_remove_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
    ]
