# Generated by Django 4.2.5 on 2023-09-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='currency',
            field=models.CharField(default='GHS', max_length=50),
        ),
    ]
